// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzO3vIgqNARbCILQ55WJOu3xnq8myBcM',
    appId: '1:289367638796:web:23b6121c49f3683261bf29',
    messagingSenderId: '289367638796',
    projectId: 'student-plan-app',
    authDomain: 'student-plan-app.firebaseapp.com',
    storageBucket: 'student-plan-app.firebasestorage.app',
    measurementId: 'G-T5N94N95B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvoHetlASzNOi586vGUb8qPC06U7PJ0Q',
    appId: '1:289367638796:android:850e9c3839ffecd761bf29',
    messagingSenderId: '289367638796',
    projectId: 'student-plan-app',
    storageBucket: 'student-plan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCudWwJIicdbIZyO63mInJF974zkLOSokc',
    appId: '1:289367638796:ios:5db368bae662ca8961bf29',
    messagingSenderId: '289367638796',
    projectId: 'student-plan-app',
    storageBucket: 'student-plan-app.firebasestorage.app',
    iosBundleId: 'com.example.studentPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCudWwJIicdbIZyO63mInJF974zkLOSokc',
    appId: '1:289367638796:ios:5db368bae662ca8961bf29',
    messagingSenderId: '289367638796',
    projectId: 'student-plan-app',
    storageBucket: 'student-plan-app.firebasestorage.app',
    iosBundleId: 'com.example.studentPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfzO3vIgqNARbCILQ55WJOu3xnq8myBcM',
    appId: '1:289367638796:web:3010604d5f792e3c61bf29',
    messagingSenderId: '289367638796',
    projectId: 'student-plan-app',
    authDomain: 'student-plan-app.firebaseapp.com',
    storageBucket: 'student-plan-app.firebasestorage.app',
    measurementId: 'G-C9X035D3YC',
  );
}
